server:
  port: ${APP_PORT:8080}
  servlet:
    context-path: /bank

spring:
  datasource:
    url: ${DB_URL:jdbc:sqlserver://localhost:1433;database=TESTDB;encrypt=false}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:p@ssw0rD!}
  liquibase:
    url: ${DB_URL:jdbc:sqlserver://localhost:1433;database=TESTDB;encrypt=false}
    user: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:p@ssw0rD!}
    default-schema: dbo
    change-log: classpath:/db/changelog/db.changelog-master.yml
    enabled: true
    drop-first: false
  jpa:
    hibernate:
      ddl-auto: none

logging:
  file:
    name: ${LOG_LOCATION:bank-app.log}
  level:
    "[com.anasdidi.bank]": ${LOG_LEVEL:INFO}
